### ISSUE TITLE
Make help menu easier to understand

### ISSUE THREAD

**Issue by ctrlsam** [mayukh18/BlindChat#11]
When using the bot I found the 'Available commands' response was slightly confusing. I believe this could be improved by changing the structure of the returned options, for example:
**Currently:** `1. quit/exit: quits from the active chat or from the waitlist
`
**Recommended:**`exit - quits from the active chat or from the waitlist`

In my opinion there is no point of the numbering unless this was also accounted when servicing the users input

**Comment by mayukh18** [comment]
Sure go ahead. If you want to do it a bit better, you can perhaps put some emojis in there too in suitable places. It'll look good too.

**Comment by SillySam** [comment]
Ok, I'll get onto it later today.

**Comment by SillySam** [comment]
I made a PR with the cleaned menu, will look into adding emoji's later tonight

**Comment by btlin1213** [comment]
is this still open?
