### ISSUE TITLE
The requested URL was not found on the server

### ISSUE THREAD

**Issue by idgm5** [mayukh18/BlindChat#19]
I'm new with flask so I don't know if I miss a step following the setup instructions, but everything is working fine except that when I access the url I receive this message instead of the 'connect' page, my chatbot doesn't send anything. 🍶 

```
Not Found
The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
```

**Comment by eljlee** [comment]
Hey, I'm totally down to see how I can help with this!
