### ISSUE TITLE
Age verification gate

### ISSUE THREAD

**Issue by mayukh18** [mayukh18/BlindChat#2]
When a new user is encountered ( user doesn't exist in users db ) ask for the age. Simple "What's your age?" Give two options "18 or over" and "under 18". First option will lead directly to the welcome message. The second option will send a message suggesting parental guidance first then go to the welcome message block.

Though the app in under facebook , their policies probably cover this but still it is better to have this check.

**Comment by Souvikray** [comment]
Anyone working on this issue?

**Comment by Pranav-Rastogi** [comment]
I would like to do this.

**Comment by mayukh18** [comment]
No one is assigned. Feel free to take this up.

**Comment by Pranav-Rastogi** [comment]
@mayukh18 Do you have a preference for tabs/spaces?

**Comment by Pranav-Rastogi** [comment]
* The function `webhook` in `app.py`, is that the only place where a new user is added?
* Which welcome screen should the user be forwarded? I mean does the code already have a welcome screen or should i make one?

**Comment by mayukh18** [comment]
A new user will hit "Get Started" that will lead to the `getstarted` postback in `postback.py`. It already has a welcome note. What will be good here is that in place of `send_newchat_prompt(id=sender)` at the end, create something like `send_age_prompt(id=sender)` that will ask for the age.

When a user clicks one of the age options, there will be another postback call which needs to be handled again in `postback.py`. You can put the two different messages for the two options there and at the end put the `send_newchat_prompt(id=sender)` to connect and complete the flow.

**Comment by ajpen** [comment]
@mayukh18 Why not get the age from the user's profile (using the date of birth) and then determine whether they are "18 or over"?

**Comment by SillySam** [comment]
Would love to help out if possible, @Pranav-Rastogi are you still working on this?

**Comment by Pranav-Rastogi** [comment]
@ajpen that would require the user to click on a button stating they have parental guidance every time they use the service but the OP wants that to be done only at the time of registration.

**Comment by Pranav-Rastogi** [comment]
@SillySam yes, I'm still working on it. I was a bit busy lately so could not make the necessary changes.

**Comment by mayukh18** [comment]
@ajpen there is a different reason. In case of messenger apps, Facebook allows access to a few info like gender, profile picture etc without explicit permission from the user. For extra info, we need to ask the user for permission which I think is not desirable we don't have any other use for it.

**Comment by rohanraj7316** [comment]
@mayukh18 is it assigned to someone

**Comment by priyankaatgithub** [comment]
@mayukh18 - Is someone working on this?

**Comment by jeffrey-hui** [comment]
> @SillySam yes, I'm still working on it. I was a bit busy lately so could not make the necessary changes.

Are you still working on this?

**Comment by GeorgeDubuque** [comment]
Anyone still working on this one?

**Comment by loykid** [comment]
Hi, is it possible for me to try working on this? Is anyone working on it?

**Comment by jitenagarwal19** [comment]
Hi,  anyone working on this or is it ok if i pick this up?

**Comment by Sudipt-panda** [comment]
Is this issue resolved? If not, can I start working on it?

**Comment by JeremiahKamama** [comment]
Is anyone assigned to this?I'd love to work on it

**Comment by chrisfoose** [comment]
I want to help with this. How can I get started?

**Comment by op23n1** [comment]
Is anyone currently working on this issue?

**Comment by arjundubey-cr** [comment]
is anyone working on this issue? I would like to work if no one is assigned to it

**Comment by Sanchayan-Bhowal** [comment]
is anyone working on this issue if no please feel free to assign me
